[package]
name = "alpha-noah"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte_string = "1.0.0"
argparse = "0.2.2"
rand = "0.8.0"