mod cli_human_player_turn_taker;
mod game_state_record_weighted_monte_carlo_turn_taker;

pub use cli_human_player_turn_taker::CLIHumanPlayerTurnTaker;
pub use game_state_record_weighted_monte_carlo_turn_taker::GameStateRecordWeightedMonteCarloTurnTaker;
